name: gcstar
version: 1.7.3.2022.08.11
release: 1
source:
    - git|https://gitlab.com/GCstar/GCstar.git: f89f1b4039dffd0551951f0b43b2cf49be22cedd
homepage: https://gitlab.com/GCstar/GCstar
license: GPL-2.0-or-later
component: office
summary: GCstar is a free open source application for managing your collections.
description: |
    Collection manager for films, music, games, books, etc.
rundeps:
    - libwww-perl
    - perl-datetime-format-strptime
    - perl-encode-locale
    - perl-gtk3-simplelist
    - perl-json
    - perl-xmlsimple
install: |
    cd gcstar
    # If an interim version is used from git commit, patch the version shown in GCstar according to this YAML version definition
    sed -i 's/\(\$VERSION = .\)[0-9\.]*/\1%version%/g' bin/gcstar

    install -Dm00755 bin/gcstar $installdir/usr/bin/gcstar
    find lib/gcstar -type f -exec install -Dm00644 "{}" "$installdir/usr/{}" \;
    find share/gcstar -type f -exec install -Dm00644 "{}" "$installdir/usr/{}" \;
    install -Dm00644 share/applications/gcstar.desktop $installdir/usr/share/applications/gcstar.desktop
    gzip -f man/gcstar.1
    install -Dm00644 man/gcstar.1.gz $installdir/usr/share/man/man1/gcstar.1.gz
    install -Dm00644 share/applications/gcstar.xml $installdir/usr/share/mime/application/x-gcstar.xml
    install -Dm00644 share/applications/gcstar.xml $installdir/usr/share/mime/packages/gcstar.xml
    install -Dm00644 share/gcstar/icons/gcstar_48x48.png $installdir/usr/share/pixmaps/gcstar.png
