name       : gcstar
version    : 1.8.0
release    : 2
source     :
    - https://gitlab.com/GCstar/GCstar/-/archive/v1.8.0/GCstar-v1.8.0.tar.gz : 6e62db6f7a4ca0b2c1bd06c9cff57dae620819dd74f7c1ce5a8d21099f352c1a
homepage   : https://gcstar.gitlab.io/
license    : GPL-2.0-or-later
component  : office
summary    : GCstar is a free open source application for managing your collections.
description: |
    Collection manager for films, music, games, books, etc.
builddeps  :
    - pkgconfig(gdk-3.0)
    - libwww-perl
    - perl-encode-locale
    - perl-gtk3-simplelist
    - perl-xmlsimple
rundeps    :
    - libwww-perl
    - perl-datetime-format-strptime
    - perl-encode-locale
    - perl-gtk3-simplelist
    - perl-json
    - perl-xmlsimple
install    : |
    ./gcstar/install --text --prefix $installdir/usr
    find $installdir/usr -type d -empty -delete
    find $installdir/usr/share/mime ! -name "*gcstar*" ! -type d -delete
